### PR TITLE
pull-maintainers-from-database-and-make-a-pr.yml: Sort maintainers

### PR DESCRIPTION
**Pull request by hzyitc**
Sort maintainers

### CODE REVIEW

**Comment by hzyitc** [comment]
@igorpecovnik

**Comment by igorpecovnik** [comment]
Missed this one ;) Sorry.

**Comment by igorpecovnik** [comment]
@hzyitc something ain't working. Can you check.

**Comment by hzyitc** [comment]
Sorry for forgetting this, will fix it.

**Pull request merged**
